### ISSUE TITLE
Uncaught TypeError: Cannot read property 'installed' of undefined in vue 1.0.21

### ISSUE THREAD

**Issue by Ridermansb** [AStaroverov/v-media-query#1]
In `main.js`

    import vMediaQuery from 'v-media-query'
    Vue.use(vMediaQuery.default)

**Comment by sainf** [comment]
That did not worked, but:

```
var vMediaQuery = require('v-media-query')
Vue.use(vMediaQuery.default)
```
works...

https://github.com/vuejs/vue-validator/issues/116

**Comment by sainf** [comment]
Works fine, thanks

**Comment by Ridermansb** [comment]
Thanks, works fine too
