### ISSUE TITLE
Vue 2.0 support

### ISSUE THREAD

**Issue by veksen** [AStaroverov/v-media-query#2]
Is there a plan to support Vue 2.0?

**Comment by AStaroverov** [comment]
I'm start work on it at shortly time.

чт, 6 окт. 2016 г., 19:19 Jean-Philippe Sirois <notifications@github.com>:

**Comment by AStaroverov** [comment]
[Updated](https://github.com/AStaroverov/v-media-query/commit/b2df8f887feccc527488a007ca2b9b938d15c4e2) to 1.0.3
Now it supported both version of Vue.
